// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.ML;
using System.Reflection;
using AudientUWP.Models;

namespace AudientUWP.Services
{
    public class ConsumeModel
    {
        // For more info on consuming ML.NET models, visit https://aka.ms/model-builder-consume
        // Method for consuming model in your app
        public static ModelOutput Predict(ModelInput input)
        {

            // Create new MLContext
            MLContext mlContext = new MLContext();
            PredictionEngine<ModelInput, ModelOutput> predEngine;

            // Load model & create prediction engine
            var assembly = Assembly.GetExecutingAssembly();
            Console.WriteLine("AUDXAM PLS");
            foreach (var res in assembly.GetManifestResourceNames())
            {
                Console.WriteLine("AUDXAM resource: " + res);
            }
            var files = Assembly.GetExecutingAssembly().GetManifestResourceNames();
            var stream2 = assembly.GetManifestResourceStream(files[0]);
            Console.WriteLine($"AUDXAM length of zip: {stream2.Length}");
            using (var stream = assembly.GetManifestResourceStream(files[0]))
            {
                ITransformer mlModel = mlContext.Model.Load(stream, out var modelInputSchema);
                predEngine = mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
            }
            // Use model to make prediction on input data
            ModelOutput result = predEngine.Predict(input);
            return result;
        }
    }
}
