// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace AudientUWP.Models
{
    public class ModelInput
    {
        [ColumnName("genre"), LoadColumn(0)]
        public string Genre { get; set; }


        [ColumnName("mfcc0_mean"), LoadColumn(1)]
        public float Mfcc0_mean { get; set; }


        [ColumnName("mfcc0_min"), LoadColumn(2)]
        public float Mfcc0_min { get; set; }


        [ColumnName("mfcc0_var"), LoadColumn(3)]
        public float Mfcc0_var { get; set; }


        [ColumnName("mfcc0_sd"), LoadColumn(4)]
        public float Mfcc0_sd { get; set; }


        [ColumnName("mfcc0_med"), LoadColumn(5)]
        public float Mfcc0_med { get; set; }


        [ColumnName("mfcc0_lq"), LoadColumn(6)]
        public float Mfcc0_lq { get; set; }


        [ColumnName("mfcc0_uq"), LoadColumn(7)]
        public float Mfcc0_uq { get; set; }


        [ColumnName("mfcc0_skew"), LoadColumn(8)]
        public float Mfcc0_skew { get; set; }


        [ColumnName("mfcc0_kurt"), LoadColumn(9)]
        public float Mfcc0_kurt { get; set; }


        [ColumnName("mfcc1_mean"), LoadColumn(10)]
        public float Mfcc1_mean { get; set; }


        [ColumnName("mfcc1_min"), LoadColumn(11)]
        public float Mfcc1_min { get; set; }


        [ColumnName("mfcc1_var"), LoadColumn(12)]
        public float Mfcc1_var { get; set; }


        [ColumnName("mfcc1_sd"), LoadColumn(13)]
        public float Mfcc1_sd { get; set; }


        [ColumnName("mfcc1_med"), LoadColumn(14)]
        public float Mfcc1_med { get; set; }


        [ColumnName("mfcc1_lq"), LoadColumn(15)]
        public float Mfcc1_lq { get; set; }


        [ColumnName("mfcc1_uq"), LoadColumn(16)]
        public float Mfcc1_uq { get; set; }


        [ColumnName("mfcc1_skew"), LoadColumn(17)]
        public float Mfcc1_skew { get; set; }


        [ColumnName("mfcc1_kurt"), LoadColumn(18)]
        public float Mfcc1_kurt { get; set; }


        [ColumnName("mfcc2_mean"), LoadColumn(19)]
        public float Mfcc2_mean { get; set; }


        [ColumnName("mfcc2_min"), LoadColumn(20)]
        public float Mfcc2_min { get; set; }


        [ColumnName("mfcc2_var"), LoadColumn(21)]
        public float Mfcc2_var { get; set; }


        [ColumnName("mfcc2_sd"), LoadColumn(22)]
        public float Mfcc2_sd { get; set; }


        [ColumnName("mfcc2_med"), LoadColumn(23)]
        public float Mfcc2_med { get; set; }


        [ColumnName("mfcc2_lq"), LoadColumn(24)]
        public float Mfcc2_lq { get; set; }


        [ColumnName("mfcc2_uq"), LoadColumn(25)]
        public float Mfcc2_uq { get; set; }


        [ColumnName("mfcc2_skew"), LoadColumn(26)]
        public float Mfcc2_skew { get; set; }


        [ColumnName("mfcc2_kurt"), LoadColumn(27)]
        public float Mfcc2_kurt { get; set; }


        [ColumnName("mfcc3_mean"), LoadColumn(28)]
        public float Mfcc3_mean { get; set; }


        [ColumnName("mfcc3_min"), LoadColumn(29)]
        public float Mfcc3_min { get; set; }


        [ColumnName("mfcc3_var"), LoadColumn(30)]
        public float Mfcc3_var { get; set; }


        [ColumnName("mfcc3_sd"), LoadColumn(31)]
        public float Mfcc3_sd { get; set; }


        [ColumnName("mfcc3_med"), LoadColumn(32)]
        public float Mfcc3_med { get; set; }


        [ColumnName("mfcc3_lq"), LoadColumn(33)]
        public float Mfcc3_lq { get; set; }


        [ColumnName("mfcc3_uq"), LoadColumn(34)]
        public float Mfcc3_uq { get; set; }


        [ColumnName("mfcc3_skew"), LoadColumn(35)]
        public float Mfcc3_skew { get; set; }


        [ColumnName("mfcc3_kurt"), LoadColumn(36)]
        public float Mfcc3_kurt { get; set; }


        [ColumnName("mfcc4_mean"), LoadColumn(37)]
        public float Mfcc4_mean { get; set; }


        [ColumnName("mfcc4_min"), LoadColumn(38)]
        public float Mfcc4_min { get; set; }


        [ColumnName("mfcc4_var"), LoadColumn(39)]
        public float Mfcc4_var { get; set; }


        [ColumnName("mfcc4_sd"), LoadColumn(40)]
        public float Mfcc4_sd { get; set; }


        [ColumnName("mfcc4_med"), LoadColumn(41)]
        public float Mfcc4_med { get; set; }


        [ColumnName("mfcc4_lq"), LoadColumn(42)]
        public float Mfcc4_lq { get; set; }


        [ColumnName("mfcc4_uq"), LoadColumn(43)]
        public float Mfcc4_uq { get; set; }


        [ColumnName("mfcc4_skew"), LoadColumn(44)]
        public float Mfcc4_skew { get; set; }


        [ColumnName("mfcc4_kurt"), LoadColumn(45)]
        public float Mfcc4_kurt { get; set; }


        [ColumnName("mfcc5_mean"), LoadColumn(46)]
        public float Mfcc5_mean { get; set; }


        [ColumnName("mfcc5_min"), LoadColumn(47)]
        public float Mfcc5_min { get; set; }


        [ColumnName("mfcc5_var"), LoadColumn(48)]
        public float Mfcc5_var { get; set; }


        [ColumnName("mfcc5_sd"), LoadColumn(49)]
        public float Mfcc5_sd { get; set; }


        [ColumnName("mfcc5_med"), LoadColumn(50)]
        public float Mfcc5_med { get; set; }


        [ColumnName("mfcc5_lq"), LoadColumn(51)]
        public float Mfcc5_lq { get; set; }


        [ColumnName("mfcc5_uq"), LoadColumn(52)]
        public float Mfcc5_uq { get; set; }


        [ColumnName("mfcc5_skew"), LoadColumn(53)]
        public float Mfcc5_skew { get; set; }


        [ColumnName("mfcc5_kurt"), LoadColumn(54)]
        public float Mfcc5_kurt { get; set; }


        [ColumnName("mfcc6_mean"), LoadColumn(55)]
        public float Mfcc6_mean { get; set; }


        [ColumnName("mfcc6_min"), LoadColumn(56)]
        public float Mfcc6_min { get; set; }


        [ColumnName("mfcc6_var"), LoadColumn(57)]
        public float Mfcc6_var { get; set; }


        [ColumnName("mfcc6_sd"), LoadColumn(58)]
        public float Mfcc6_sd { get; set; }


        [ColumnName("mfcc6_med"), LoadColumn(59)]
        public float Mfcc6_med { get; set; }


        [ColumnName("mfcc6_lq"), LoadColumn(60)]
        public float Mfcc6_lq { get; set; }


        [ColumnName("mfcc6_uq"), LoadColumn(61)]
        public float Mfcc6_uq { get; set; }


        [ColumnName("mfcc6_skew"), LoadColumn(62)]
        public float Mfcc6_skew { get; set; }


        [ColumnName("mfcc6_kurt"), LoadColumn(63)]
        public float Mfcc6_kurt { get; set; }


        [ColumnName("mfcc7_mean"), LoadColumn(64)]
        public float Mfcc7_mean { get; set; }


        [ColumnName("mfcc7_min"), LoadColumn(65)]
        public float Mfcc7_min { get; set; }


        [ColumnName("mfcc7_var"), LoadColumn(66)]
        public float Mfcc7_var { get; set; }


        [ColumnName("mfcc7_sd"), LoadColumn(67)]
        public float Mfcc7_sd { get; set; }


        [ColumnName("mfcc7_med"), LoadColumn(68)]
        public float Mfcc7_med { get; set; }


        [ColumnName("mfcc7_lq"), LoadColumn(69)]
        public float Mfcc7_lq { get; set; }


        [ColumnName("mfcc7_uq"), LoadColumn(70)]
        public float Mfcc7_uq { get; set; }


        [ColumnName("mfcc7_skew"), LoadColumn(71)]
        public float Mfcc7_skew { get; set; }


        [ColumnName("mfcc7_kurt"), LoadColumn(72)]
        public float Mfcc7_kurt { get; set; }


        [ColumnName("mfcc8_mean"), LoadColumn(73)]
        public float Mfcc8_mean { get; set; }


        [ColumnName("mfcc8_min"), LoadColumn(74)]
        public float Mfcc8_min { get; set; }


        [ColumnName("mfcc8_var"), LoadColumn(75)]
        public float Mfcc8_var { get; set; }


        [ColumnName("mfcc8_sd"), LoadColumn(76)]
        public float Mfcc8_sd { get; set; }


        [ColumnName("mfcc8_med"), LoadColumn(77)]
        public float Mfcc8_med { get; set; }


        [ColumnName("mfcc8_lq"), LoadColumn(78)]
        public float Mfcc8_lq { get; set; }


        [ColumnName("mfcc8_uq"), LoadColumn(79)]
        public float Mfcc8_uq { get; set; }


        [ColumnName("mfcc8_skew"), LoadColumn(80)]
        public float Mfcc8_skew { get; set; }


        [ColumnName("mfcc8_kurt"), LoadColumn(81)]
        public float Mfcc8_kurt { get; set; }


        [ColumnName("mfcc9_mean"), LoadColumn(82)]
        public float Mfcc9_mean { get; set; }


        [ColumnName("mfcc9_min"), LoadColumn(83)]
        public float Mfcc9_min { get; set; }


        [ColumnName("mfcc9_var"), LoadColumn(84)]
        public float Mfcc9_var { get; set; }


        [ColumnName("mfcc9_sd"), LoadColumn(85)]
        public float Mfcc9_sd { get; set; }


        [ColumnName("mfcc9_med"), LoadColumn(86)]
        public float Mfcc9_med { get; set; }


        [ColumnName("mfcc9_lq"), LoadColumn(87)]
        public float Mfcc9_lq { get; set; }


        [ColumnName("mfcc9_uq"), LoadColumn(88)]
        public float Mfcc9_uq { get; set; }


        [ColumnName("mfcc9_skew"), LoadColumn(89)]
        public float Mfcc9_skew { get; set; }


        [ColumnName("mfcc9_kurt"), LoadColumn(90)]
        public float Mfcc9_kurt { get; set; }


        [ColumnName("mfcc10_mean"), LoadColumn(91)]
        public float Mfcc10_mean { get; set; }


        [ColumnName("mfcc10_min"), LoadColumn(92)]
        public float Mfcc10_min { get; set; }


        [ColumnName("mfcc10_var"), LoadColumn(93)]
        public float Mfcc10_var { get; set; }


        [ColumnName("mfcc10_sd"), LoadColumn(94)]
        public float Mfcc10_sd { get; set; }


        [ColumnName("mfcc10_med"), LoadColumn(95)]
        public float Mfcc10_med { get; set; }


        [ColumnName("mfcc10_lq"), LoadColumn(96)]
        public float Mfcc10_lq { get; set; }


        [ColumnName("mfcc10_uq"), LoadColumn(97)]
        public float Mfcc10_uq { get; set; }


        [ColumnName("mfcc10_skew"), LoadColumn(98)]
        public float Mfcc10_skew { get; set; }


        [ColumnName("mfcc10_kurt"), LoadColumn(99)]
        public float Mfcc10_kurt { get; set; }


        [ColumnName("mfcc11_mean"), LoadColumn(100)]
        public float Mfcc11_mean { get; set; }


        [ColumnName("mfcc11_min"), LoadColumn(101)]
        public float Mfcc11_min { get; set; }


        [ColumnName("mfcc11_var"), LoadColumn(102)]
        public float Mfcc11_var { get; set; }


        [ColumnName("mfcc11_sd"), LoadColumn(103)]
        public float Mfcc11_sd { get; set; }


        [ColumnName("mfcc11_med"), LoadColumn(104)]
        public float Mfcc11_med { get; set; }


        [ColumnName("mfcc11_lq"), LoadColumn(105)]
        public float Mfcc11_lq { get; set; }


        [ColumnName("mfcc11_uq"), LoadColumn(106)]
        public float Mfcc11_uq { get; set; }


        [ColumnName("mfcc11_skew"), LoadColumn(107)]
        public float Mfcc11_skew { get; set; }


        [ColumnName("mfcc11_kurt"), LoadColumn(108)]
        public float Mfcc11_kurt { get; set; }


        [ColumnName("mfcc12_mean"), LoadColumn(109)]
        public float Mfcc12_mean { get; set; }


        [ColumnName("mfcc12_min"), LoadColumn(110)]
        public float Mfcc12_min { get; set; }


        [ColumnName("mfcc12_var"), LoadColumn(111)]
        public float Mfcc12_var { get; set; }


        [ColumnName("mfcc12_sd"), LoadColumn(112)]
        public float Mfcc12_sd { get; set; }


        [ColumnName("mfcc12_med"), LoadColumn(113)]
        public float Mfcc12_med { get; set; }


        [ColumnName("mfcc12_lq"), LoadColumn(114)]
        public float Mfcc12_lq { get; set; }


        [ColumnName("mfcc12_uq"), LoadColumn(115)]
        public float Mfcc12_uq { get; set; }


        [ColumnName("mfcc12_skew"), LoadColumn(116)]
        public float Mfcc12_skew { get; set; }


        [ColumnName("mfcc12_kurt"), LoadColumn(117)]
        public float Mfcc12_kurt { get; set; }


        [ColumnName("mfcc13_mean"), LoadColumn(118)]
        public float Mfcc13_mean { get; set; }


        [ColumnName("mfcc13_min"), LoadColumn(119)]
        public float Mfcc13_min { get; set; }


        [ColumnName("mfcc13_var"), LoadColumn(120)]
        public float Mfcc13_var { get; set; }


        [ColumnName("mfcc13_sd"), LoadColumn(121)]
        public float Mfcc13_sd { get; set; }


        [ColumnName("mfcc13_med"), LoadColumn(122)]
        public float Mfcc13_med { get; set; }


        [ColumnName("mfcc13_lq"), LoadColumn(123)]
        public float Mfcc13_lq { get; set; }


        [ColumnName("mfcc13_uq"), LoadColumn(124)]
        public float Mfcc13_uq { get; set; }


        [ColumnName("mfcc13_skew"), LoadColumn(125)]
        public float Mfcc13_skew { get; set; }


        [ColumnName("mfcc13_kurt"), LoadColumn(126)]
        public float Mfcc13_kurt { get; set; }


        [ColumnName("mfcc14_mean"), LoadColumn(127)]
        public float Mfcc14_mean { get; set; }


        [ColumnName("mfcc14_min"), LoadColumn(128)]
        public float Mfcc14_min { get; set; }


        [ColumnName("mfcc14_var"), LoadColumn(129)]
        public float Mfcc14_var { get; set; }


        [ColumnName("mfcc14_sd"), LoadColumn(130)]
        public float Mfcc14_sd { get; set; }


        [ColumnName("mfcc14_med"), LoadColumn(131)]
        public float Mfcc14_med { get; set; }


        [ColumnName("mfcc14_lq"), LoadColumn(132)]
        public float Mfcc14_lq { get; set; }


        [ColumnName("mfcc14_uq"), LoadColumn(133)]
        public float Mfcc14_uq { get; set; }


        [ColumnName("mfcc14_skew"), LoadColumn(134)]
        public float Mfcc14_skew { get; set; }


        [ColumnName("mfcc14_kurt"), LoadColumn(135)]
        public float Mfcc14_kurt { get; set; }


        [ColumnName("mfcc15_mean"), LoadColumn(136)]
        public float Mfcc15_mean { get; set; }


        [ColumnName("mfcc15_min"), LoadColumn(137)]
        public float Mfcc15_min { get; set; }


        [ColumnName("mfcc15_var"), LoadColumn(138)]
        public float Mfcc15_var { get; set; }


        [ColumnName("mfcc15_sd"), LoadColumn(139)]
        public float Mfcc15_sd { get; set; }


        [ColumnName("mfcc15_med"), LoadColumn(140)]
        public float Mfcc15_med { get; set; }


        [ColumnName("mfcc15_lq"), LoadColumn(141)]
        public float Mfcc15_lq { get; set; }


        [ColumnName("mfcc15_uq"), LoadColumn(142)]
        public float Mfcc15_uq { get; set; }


        [ColumnName("mfcc15_skew"), LoadColumn(143)]
        public float Mfcc15_skew { get; set; }


        [ColumnName("mfcc15_kurt"), LoadColumn(144)]
        public float Mfcc15_kurt { get; set; }


        [ColumnName("mfcc16_mean"), LoadColumn(145)]
        public float Mfcc16_mean { get; set; }


        [ColumnName("mfcc16_min"), LoadColumn(146)]
        public float Mfcc16_min { get; set; }


        [ColumnName("mfcc16_var"), LoadColumn(147)]
        public float Mfcc16_var { get; set; }


        [ColumnName("mfcc16_sd"), LoadColumn(148)]
        public float Mfcc16_sd { get; set; }


        [ColumnName("mfcc16_med"), LoadColumn(149)]
        public float Mfcc16_med { get; set; }


        [ColumnName("mfcc16_lq"), LoadColumn(150)]
        public float Mfcc16_lq { get; set; }


        [ColumnName("mfcc16_uq"), LoadColumn(151)]
        public float Mfcc16_uq { get; set; }


        [ColumnName("mfcc16_skew"), LoadColumn(152)]
        public float Mfcc16_skew { get; set; }


        [ColumnName("mfcc16_kurt"), LoadColumn(153)]
        public float Mfcc16_kurt { get; set; }


        [ColumnName("mfcc17_mean"), LoadColumn(154)]
        public float Mfcc17_mean { get; set; }


        [ColumnName("mfcc17_min"), LoadColumn(155)]
        public float Mfcc17_min { get; set; }


        [ColumnName("mfcc17_var"), LoadColumn(156)]
        public float Mfcc17_var { get; set; }


        [ColumnName("mfcc17_sd"), LoadColumn(157)]
        public float Mfcc17_sd { get; set; }


        [ColumnName("mfcc17_med"), LoadColumn(158)]
        public float Mfcc17_med { get; set; }


        [ColumnName("mfcc17_lq"), LoadColumn(159)]
        public float Mfcc17_lq { get; set; }


        [ColumnName("mfcc17_uq"), LoadColumn(160)]
        public float Mfcc17_uq { get; set; }


        [ColumnName("mfcc17_skew"), LoadColumn(161)]
        public float Mfcc17_skew { get; set; }


        [ColumnName("mfcc17_kurt"), LoadColumn(162)]
        public float Mfcc17_kurt { get; set; }


        [ColumnName("mfcc18_mean"), LoadColumn(163)]
        public float Mfcc18_mean { get; set; }


        [ColumnName("mfcc18_min"), LoadColumn(164)]
        public float Mfcc18_min { get; set; }


        [ColumnName("mfcc18_var"), LoadColumn(165)]
        public float Mfcc18_var { get; set; }


        [ColumnName("mfcc18_sd"), LoadColumn(166)]
        public float Mfcc18_sd { get; set; }


        [ColumnName("mfcc18_med"), LoadColumn(167)]
        public float Mfcc18_med { get; set; }


        [ColumnName("mfcc18_lq"), LoadColumn(168)]
        public float Mfcc18_lq { get; set; }


        [ColumnName("mfcc18_uq"), LoadColumn(169)]
        public float Mfcc18_uq { get; set; }


        [ColumnName("mfcc18_skew"), LoadColumn(170)]
        public float Mfcc18_skew { get; set; }


        [ColumnName("mfcc18_kurt"), LoadColumn(171)]
        public float Mfcc18_kurt { get; set; }


        [ColumnName("mfcc19_mean"), LoadColumn(172)]
        public float Mfcc19_mean { get; set; }


        [ColumnName("mfcc19_min"), LoadColumn(173)]
        public float Mfcc19_min { get; set; }


        [ColumnName("mfcc19_var"), LoadColumn(174)]
        public float Mfcc19_var { get; set; }


        [ColumnName("mfcc19_sd"), LoadColumn(175)]
        public float Mfcc19_sd { get; set; }


        [ColumnName("mfcc19_med"), LoadColumn(176)]
        public float Mfcc19_med { get; set; }


        [ColumnName("mfcc19_lq"), LoadColumn(177)]
        public float Mfcc19_lq { get; set; }


        [ColumnName("mfcc19_uq"), LoadColumn(178)]
        public float Mfcc19_uq { get; set; }


        [ColumnName("mfcc19_skew"), LoadColumn(179)]
        public float Mfcc19_skew { get; set; }


        [ColumnName("mfcc19_kurt"), LoadColumn(180)]
        public float Mfcc19_kurt { get; set; }


        [ColumnName("mfcc20_mean"), LoadColumn(181)]
        public float Mfcc20_mean { get; set; }


        [ColumnName("mfcc20_min"), LoadColumn(182)]
        public float Mfcc20_min { get; set; }


        [ColumnName("mfcc20_var"), LoadColumn(183)]
        public float Mfcc20_var { get; set; }


        [ColumnName("mfcc20_sd"), LoadColumn(184)]
        public float Mfcc20_sd { get; set; }


        [ColumnName("mfcc20_med"), LoadColumn(185)]
        public float Mfcc20_med { get; set; }


        [ColumnName("mfcc20_lq"), LoadColumn(186)]
        public float Mfcc20_lq { get; set; }


        [ColumnName("mfcc20_uq"), LoadColumn(187)]
        public float Mfcc20_uq { get; set; }


        [ColumnName("mfcc20_skew"), LoadColumn(188)]
        public float Mfcc20_skew { get; set; }


        [ColumnName("mfcc20_kurt"), LoadColumn(189)]
        public float Mfcc20_kurt { get; set; }


        [ColumnName("mfcc21_mean"), LoadColumn(190)]
        public float Mfcc21_mean { get; set; }


        [ColumnName("mfcc21_min"), LoadColumn(191)]
        public float Mfcc21_min { get; set; }


        [ColumnName("mfcc21_var"), LoadColumn(192)]
        public float Mfcc21_var { get; set; }


        [ColumnName("mfcc21_sd"), LoadColumn(193)]
        public float Mfcc21_sd { get; set; }


        [ColumnName("mfcc21_med"), LoadColumn(194)]
        public float Mfcc21_med { get; set; }


        [ColumnName("mfcc21_lq"), LoadColumn(195)]
        public float Mfcc21_lq { get; set; }


        [ColumnName("mfcc21_uq"), LoadColumn(196)]
        public float Mfcc21_uq { get; set; }


        [ColumnName("mfcc21_skew"), LoadColumn(197)]
        public float Mfcc21_skew { get; set; }


        [ColumnName("mfcc21_kurt"), LoadColumn(198)]
        public float Mfcc21_kurt { get; set; }


        [ColumnName("mfcc22_mean"), LoadColumn(199)]
        public float Mfcc22_mean { get; set; }


        [ColumnName("mfcc22_min"), LoadColumn(200)]
        public float Mfcc22_min { get; set; }


        [ColumnName("mfcc22_var"), LoadColumn(201)]
        public float Mfcc22_var { get; set; }


        [ColumnName("mfcc22_sd"), LoadColumn(202)]
        public float Mfcc22_sd { get; set; }


        [ColumnName("mfcc22_med"), LoadColumn(203)]
        public float Mfcc22_med { get; set; }


        [ColumnName("mfcc22_lq"), LoadColumn(204)]
        public float Mfcc22_lq { get; set; }


        [ColumnName("mfcc22_uq"), LoadColumn(205)]
        public float Mfcc22_uq { get; set; }


        [ColumnName("mfcc22_skew"), LoadColumn(206)]
        public float Mfcc22_skew { get; set; }


        [ColumnName("mfcc22_kurt"), LoadColumn(207)]
        public float Mfcc22_kurt { get; set; }


        [ColumnName("mfcc23_mean"), LoadColumn(208)]
        public float Mfcc23_mean { get; set; }


        [ColumnName("mfcc23_min"), LoadColumn(209)]
        public float Mfcc23_min { get; set; }


        [ColumnName("mfcc23_var"), LoadColumn(210)]
        public float Mfcc23_var { get; set; }


        [ColumnName("mfcc23_sd"), LoadColumn(211)]
        public float Mfcc23_sd { get; set; }


        [ColumnName("mfcc23_med"), LoadColumn(212)]
        public float Mfcc23_med { get; set; }


        [ColumnName("mfcc23_lq"), LoadColumn(213)]
        public float Mfcc23_lq { get; set; }


        [ColumnName("mfcc23_uq"), LoadColumn(214)]
        public float Mfcc23_uq { get; set; }


        [ColumnName("mfcc23_skew"), LoadColumn(215)]
        public float Mfcc23_skew { get; set; }


        [ColumnName("mfcc23_kurt"), LoadColumn(216)]
        public float Mfcc23_kurt { get; set; }


        [ColumnName("energy_mean"), LoadColumn(217)]
        public float Energy_mean { get; set; }


        [ColumnName("energy_min"), LoadColumn(218)]
        public float Energy_min { get; set; }


        [ColumnName("energy_var"), LoadColumn(219)]
        public float Energy_var { get; set; }


        [ColumnName("energy_sd"), LoadColumn(220)]
        public float Energy_sd { get; set; }


        [ColumnName("energy_med"), LoadColumn(221)]
        public float Energy_med { get; set; }


        [ColumnName("energy_lq"), LoadColumn(222)]
        public float Energy_lq { get; set; }


        [ColumnName("energy_uq"), LoadColumn(223)]
        public float Energy_uq { get; set; }


        [ColumnName("energy_skew"), LoadColumn(224)]
        public float Energy_skew { get; set; }


        [ColumnName("energy_kurt"), LoadColumn(225)]
        public float Energy_kurt { get; set; }


        [ColumnName("rms_mean"), LoadColumn(226)]
        public float Rms_mean { get; set; }


        [ColumnName("rms_min"), LoadColumn(227)]
        public float Rms_min { get; set; }


        [ColumnName("rms_var"), LoadColumn(228)]
        public float Rms_var { get; set; }


        [ColumnName("rms_sd"), LoadColumn(229)]
        public float Rms_sd { get; set; }


        [ColumnName("rms_med"), LoadColumn(230)]
        public float Rms_med { get; set; }


        [ColumnName("rms_lq"), LoadColumn(231)]
        public float Rms_lq { get; set; }


        [ColumnName("rms_uq"), LoadColumn(232)]
        public float Rms_uq { get; set; }


        [ColumnName("rms_skew"), LoadColumn(233)]
        public float Rms_skew { get; set; }


        [ColumnName("rms_kurt"), LoadColumn(234)]
        public float Rms_kurt { get; set; }


        [ColumnName("zcr_mean"), LoadColumn(235)]
        public float Zcr_mean { get; set; }


        [ColumnName("zcr_min"), LoadColumn(236)]
        public float Zcr_min { get; set; }


        [ColumnName("zcr_var"), LoadColumn(237)]
        public float Zcr_var { get; set; }


        [ColumnName("zcr_sd"), LoadColumn(238)]
        public float Zcr_sd { get; set; }


        [ColumnName("zcr_med"), LoadColumn(239)]
        public float Zcr_med { get; set; }


        [ColumnName("zcr_lq"), LoadColumn(240)]
        public float Zcr_lq { get; set; }


        [ColumnName("zcr_uq"), LoadColumn(241)]
        public float Zcr_uq { get; set; }


        [ColumnName("zcr_skew"), LoadColumn(242)]
        public float Zcr_skew { get; set; }


        [ColumnName("zcr_kurt"), LoadColumn(243)]
        public float Zcr_kurt { get; set; }


        [ColumnName("entropy_mean"), LoadColumn(244)]
        public float Entropy_mean { get; set; }


        [ColumnName("entropy_min"), LoadColumn(245)]
        public float Entropy_min { get; set; }


        [ColumnName("entropy_var"), LoadColumn(246)]
        public float Entropy_var { get; set; }


        [ColumnName("entropy_sd"), LoadColumn(247)]
        public float Entropy_sd { get; set; }


        [ColumnName("entropy_med"), LoadColumn(248)]
        public float Entropy_med { get; set; }


        [ColumnName("entropy_lq"), LoadColumn(249)]
        public float Entropy_lq { get; set; }


        [ColumnName("entropy_uq"), LoadColumn(250)]
        public float Entropy_uq { get; set; }


        [ColumnName("entropy_skew"), LoadColumn(251)]
        public float Entropy_skew { get; set; }


        [ColumnName("entropy_kurt"), LoadColumn(252)]
        public float Entropy_kurt { get; set; }


        [ColumnName("centroid"), LoadColumn(253)]
        public float Centroid { get; set; }


        [ColumnName("spread"), LoadColumn(254)]
        public float Spread { get; set; }


        [ColumnName("flatness"), LoadColumn(255)]
        public float Flatness { get; set; }


        [ColumnName("noiseness"), LoadColumn(256)]
        public float Noiseness { get; set; }


        [ColumnName("roloff"), LoadColumn(257)]
        public float Roloff { get; set; }


        [ColumnName("crest"), LoadColumn(258)]
        public float Crest { get; set; }


        [ColumnName("decrease"), LoadColumn(259)]
        public float Decrease { get; set; }


        [ColumnName("spectral_entropy"), LoadColumn(260)]
        public float Spectral_entropy { get; set; }


    }
}
